services:
  postgres:
    image: postgres:16-alpine
    container_name: image-gallery-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gallery
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  minio:
    image: minio/minio
    container_name: gallery-container
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ~/minio_data:/data
    command: server /data --console-address ":9001"
  minio-init:
    image: minio/mc
    depends_on:
      - minio
    environment:
      - GALLERY_BUCKET_NAME=${GALLERY_BUCKET_NAME}
      - GALLERY_SCALED_BUCKET_NAME=${GALLERY_SCALED_BUCKET_NAME}
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set local http://minio:9000 minioadmin minioadmin) do echo 'Waiting for MinIO...' && sleep 1; done;
      /usr/bin/mc mb --ignore-existing local/$$GALLERY_BUCKET_NAME;
      /usr/bin/mc mb --ignore-existing local/$$GALLERY_SCALED_BUCKET_NAME;
      /usr/bin/mc anonymous set download local/$$GALLERY_BUCKET_NAME;
      /usr/bin/mc anonymous set download local/$$GALLERY_SCALED_BUCKET_NAME;
      exit 0;
      "

volumes:
  postgres-data:
  minio_data: